export const site = {
  name: "Guzal Opa Education",
  shortName: "Guzal Opa",
  url: "https://guzalopa.uz",
  tagline: "Xorijda ta'lim bo'yicha ishonchli maslahatchingiz",
  description:
    "Guzal Opa Education — Singapur, Bali va Qatar/Dubaydagi ta'lim imkoniyatlari bo'yicha yosh talabalarga yo'l-yo'riq. Universitetga kirish, talabalik vizasi va tayyorgarlik dasturlari bo'yicha shaffof maslahat.",
  keywords: [
    "xorijda ta'lim",
    "Singapurda o'qish",
    "talabalik vizasi",
    "universitetga kirish",
    "Bali tayyorgarlik dasturi",
    "Qatar Dubai ish imkoniyatlari",
    "study abroad Uzbekistan",
    "Singapore study consulting",
    "education consulting",
    "Guzal Opa",
  ],
  locale: "uz_UZ",
  author: "Guzal Opa Education",
  contact: {
    phone: "+998 90 123 45 67",
    email: "hello@guzalopa.uz",
    telegram: "@guzalopa_edu",
    address: "Toshkent sh., O'zbekiston",
  },
  social: {
    telegram: "https://t.me/guzalopa_edu",
    instagram: "https://instagram.com/guzalopa.edu",
    youtube: "https://youtube.com/@guzalopa",
  },
  nav: [
    { label: "Bosh sahifa", href: "#home" },
    { label: "Xizmatlar", href: "#services" },
    { label: "Yangiliklar", href: "#news" },
    { label: "Jarayon", href: "#process" },
    { label: "Nega biz", href: "#why" },
    { label: "Savollar", href: "#faq" },
    { label: "Bog'lanish", href: "#contact" },
  ],
} as const;
